using Xamarin.Forms;
using System.Linq;

namespace TouchEffect.Extensions
{
    public static class TouchEffExtensions
    {
        public static TouchEff GetTouchEff(this BindableObject bindable)
        {
            var effects = (bindable as VisualElement)?.Effects?.OfType<TouchEff>();
            return effects?.FirstOrDefault(x => !x.IsAutoGenerated)
                ?? effects?.FirstOrDefault();
        }

        internal static int AdjustDurationMultiplier(this int duration, double? multiplier)
            => multiplier.HasValue
                ? (int)(multiplier.Value * duration)
                : duration;
    }
}
